name: monitoring-sgr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - streamlit=1.29.0
  - pandas=2.1.4
  - numpy>=1.24.3
  - pip:
    - folium==0.15.0
    - streamlit-folium==0.15.0
    - jinja2>=3.1.2
    - branca>=0.6.0
    - protobuf>=3.20.0
